### PR TITLE
refactor: Common sponsors footer

### PR DESCRIPTION
**Pull request by Alystrasz**
Just like #6, this PR removes duplication in `2025` pages, exporting the sponsors footer into a dedicated template, that is only included for `/2025` pages.

##### Screenshot of the component appearing at the bottom of all `2025` pages

image

### CODE REVIEW

**Comment by basvdheuvel** [comment]
Looks good to me.

Only remark is that we now have two places where we check for specifically "/2025/".
This will become a very cumbersome thing to maintain as the years go by.
Can we refactor this to exclude all prior years instead? Other suggestions are welcome too, of course.

**Comment by Alystrasz** [comment]
I guess if we wanted to have the same "common banner+footer" for 2026 and all future editions of DisCoTec, we could indeed write something along `if year >= 2025`; this would however impose each new website to provide its own banner and footer.
Please note I made both modifications (banner + footer) with next year's edition in mind, and didn't want to impact past and future versions of the website, hence the `year == 2025` checks.

**Comment by Alystrasz** [comment]
> Makes sense. Then I'd suggest to incorporate the check in `_layouts/default.html`. This way future years can easily reuse the menu/footer, and design year-specific versions in the `_includes/...` files.

Fair!
Do you want me to include this change in this PR or in another one?

**Comment by basvdheuvel** [comment]
Including it here is fine, thanks!

**Comment by Alystrasz** [comment]
> Including it here is fine, thanks!

Implemented in 76aafda24a87814d34076797bf1322fee8789dac.

**Pull request merged**
